dist: trusty
sudo: required
language: node_js
node_js:
- '7'

cache:
  yarn: true
  directories:
  - node_modules
  - functions/node_modules

before_deploy:
- "yarn build"
- "( cd functions ; yarn install )"

deploy:
  provider: firebase
  skip_cleanup: true
  token:
    secure: "Hgl437bggVIuPucfSp4ZM5AKGUPZKRSdPoS76ta7t0/TMOpRKGmZwWQPaF7lL61R2U9XHEcQjC7P4m8cFFxq4CpZq4uHLJFAln4OCUvLp9G+C880SFUT1KWpepxi4/s2haWK0L8tE1B5vKRP43GFeke5Bh5tE6sgznwFTOBDjRF3NSh5g3Tpv0Hxi/uW+jCM4jNfpbawN3307KSUXBq4FhH1WewszuEexLbxA68TVic4i3kAC5pw4p2nvyZFa3EXpaDcPAhkfP/yUmikIsVQKdPkeMozqbC1vDqtNRKe6Wn6uxHBOIm9xRgMAN5kyRurar/gb3gvGhkatxFgug6bYh4MO2MC1kfKwSYsUXxKCTAv90kuLH+aOpze0F0vTrKDNhH5mMTRIZUONAgTB063iWTK09nMKhkZgp/HTLTHB8r80vLPlXPvj+lD/UpIVvCebYI6PuuAvwIyZCUvKb4lP+yftUj1cLNDcR5V5Kk8xlZDfcdeaym6OkO6FEOsH7i3yuJVgm77w7NzuNkTze1qJSCqHGqatEV1EH1z8ZqXlArxZzNxAN6KPbIqwh97PrB+YlGOeL2FmpnmFzE5krmKROAiB/wELw2FDnHgw1V2GYtu49BJyFX7BK1z0yOb/FZtqkGW76Lk4QwxZco1+be0NJSenZ7cv11iMFmyvp7E0+Y="
